declare const styles: {
  readonly root: string;
  readonly searchRow: string;
  readonly searchInput: string;
  readonly loading: string;
  readonly error: string;
  readonly empty: string;
  readonly groupList: string;
  readonly group: string;
  readonly groupHeader: string;
  readonly groupLabel: string;
  readonly groupCount: string;
  readonly groupEmpty: string;
  readonly list: string;
  readonly row: string;
  readonly rowActive: string;
  readonly rowPrimary: string;
  readonly rowTitle: string;
  readonly rowAge: string;
  readonly rowSecondary: string;
  readonly rowProject: string;
  readonly rowSeparator: string;
  readonly rowContentType: string;
  readonly rowTertiary: string;
  readonly rowAttribution: string;
  readonly highlight: string;
};
export default styles;
