declare const styles: {
  readonly hero: string;
  readonly backgroundImage: string;
  readonly backgroundScrim: string;
  readonly ambientLayer: string;
  readonly vignette: string;
  readonly warmShift: string;
  readonly edgeHighlight: string;
  readonly grain: string;
  readonly contentLayer: string;
  readonly brandLockup: string;
  readonly brandLogo: string;
  readonly brandLabel: string;
  readonly identityBlock: string;
  readonly tagline: string;
  readonly greetingBlock: string;
  readonly greetingPrefix: string;
  readonly greetingName: string;
};
export default styles;
