import type { IListDefinition } from '../services/sharepoint-service.js';

/**
 * W0-G2-T06: Financial-family list definitions for provisioning saga Step 4.
 * Separate module from core HB_INTEL_LIST_DEFINITIONS to preserve G1 regression guard.
 * T07 will combine core + family arrays for provisioning dispatch.
 *
 * 5 lists: 1 parent (Buyout Log), 1 child (Buyout Bid Lines), 3 flat.
 * Cross-family references use pid-based queries and plain Text fields — NOT Lookup columns.
 */
export const FINANCIAL_LIST_DEFINITIONS: IListDefinition[] = [
  {
    title: 'Buyout Log',
    description: 'Tracks pre-award bidding intelligence — scope packages, bid solicitation, award decisions, and contract execution status.',
    template: 100,
    listFamily: 'financial',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Scope Package Name', type: 'Text', required: true },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['Pending Bids', 'Bids Received', 'Under Review', 'Awarded', 'Executed', 'On Hold'] },
      { internalName: 'Division', displayName: 'Division', type: 'Choice', choices: ['Division 01', 'Division 02', 'Division 03', 'Division 04', 'Division 05', 'Division 06', 'Division 07', 'Division 08', 'Division 09', 'Division 10', 'Division 11', 'Division 12', 'Division 13', 'Division 14', 'Division 15', 'Division 16', 'Other'] },
      { internalName: 'BudgetAmount', displayName: 'Budget Amount', type: 'Number' },
      { internalName: 'AwardAmount', displayName: 'Award Amount', type: 'Number' },
      { internalName: 'AwardedTo', displayName: 'Awarded To', type: 'Text' },
      { internalName: 'AwardDate', displayName: 'Award Date', type: 'DateTime' },
      { internalName: 'ContractExecutedDate', displayName: 'Contract Executed Date', type: 'DateTime' },
      { internalName: 'NTPDate', displayName: 'NTP Date', type: 'DateTime' },
      { internalName: 'ScheduledStartDate', displayName: 'Scheduled Start Date', type: 'DateTime' },
      { internalName: 'ScheduledCompletionDate', displayName: 'Scheduled Completion Date', type: 'DateTime' },
      { internalName: 'InsuranceCOIReceived', displayName: 'Insurance COI Received', type: 'Boolean' },
      { internalName: 'BondingRequired', displayName: 'Bonding Required', type: 'Boolean' },
      { internalName: 'BondReceived', displayName: 'Bond Received', type: 'Boolean' },
      { internalName: 'ProcoreSubcontractId', displayName: 'Procore Subcontract ID', type: 'Text' },
      { internalName: 'Notes', displayName: 'Notes', type: 'MultiLineText' },
    ],
  },
  {
    title: 'Buyout Bid Lines',
    description: 'Child records of Buyout Log — individual bids received for each scope package.',
    template: 100,
    listFamily: 'financial',
    provisioningOrder: 20,
    parentListTitle: 'Buyout Log',
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Bid Description', type: 'Text', required: true },
      { internalName: 'ParentRecord', displayName: 'Buyout Log', type: 'Lookup', required: true, lookupListTitle: 'Buyout Log', lookupFieldName: 'ID' },
      { internalName: 'SubcontractorName', displayName: 'Subcontractor Name', type: 'Text', required: true },
      { internalName: 'BidAmount', displayName: 'Bid Amount', type: 'Number' },
      { internalName: 'BidDate', displayName: 'Bid Date', type: 'DateTime' },
      { internalName: 'BidStatus', displayName: 'Bid Status', type: 'Choice', choices: ['Invited', 'Pending', 'Submitted', 'Declined', 'Awarded', 'Alternate', 'Rejected'] },
      { internalName: 'Scope', displayName: 'Scope', type: 'MultiLineText' },
      { internalName: 'ContactName', displayName: 'Contact Name', type: 'Text' },
      { internalName: 'ContactEmail', displayName: 'Contact Email', type: 'Text' },
      { internalName: 'Notes', displayName: 'Notes', type: 'MultiLineText' },
    ],
  },
  {
    title: 'Draw Schedule',
    description: 'Simplified row-per-budget-line draw schedule tracking — contract budget, current forecast, billed-to-date, and remaining budget per cost code.',
    template: 100,
    listFamily: 'financial',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Line Item Description', type: 'Text', required: true },
      { internalName: 'CostCode', displayName: 'Cost Code', type: 'Text' },
      { internalName: 'ContractBudget', displayName: 'Contract Budget', type: 'Number' },
      { internalName: 'CurrentForecast', displayName: 'Current Forecast', type: 'Number' },
      { internalName: 'BilledToDate', displayName: 'Billed to Date', type: 'Number' },
      { internalName: 'RemainingBudget', displayName: 'Remaining Budget', type: 'Number' },
      { internalName: 'PercentComplete', displayName: 'Percent Complete', type: 'Number' },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['On Track', 'At Risk', 'Over Budget', 'Complete'] },
      { internalName: 'LastUpdated', displayName: 'Last Updated', type: 'DateTime' },
      { internalName: 'Notes', displayName: 'Notes', type: 'MultiLineText' },
    ],
  },
  {
    title: 'Financial Forecast Status',
    description: 'Monthly forecast compliance checklist — tracks whether each forecast period has been submitted with all required inputs updated.',
    template: 100,
    listFamily: 'financial',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Forecast Period', type: 'Text', required: true },
      { internalName: 'ForecastMonth', displayName: 'Forecast Month', type: 'DateTime', required: true },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['Not Started', 'In Progress', 'Submitted', 'Approved'] },
      { internalName: 'ProcoreBudgetUpdated', displayName: 'Procore Budget Updated', type: 'Boolean' },
      { internalName: 'ForecastSummaryComplete', displayName: 'Forecast Summary Complete', type: 'Boolean' },
      { internalName: 'VendorQuotesReceived', displayName: 'Vendor Quotes Received', type: 'Boolean' },
      { internalName: 'GCGRUpdated', displayName: 'GC-GR Updated', type: 'Boolean' },
      { internalName: 'ContractType', displayName: 'Contract Type', type: 'Choice', choices: ['CM/GMP', 'Lump Sum', 'Cost Plus', 'Other'] },
      { internalName: 'ProjectType', displayName: 'Project Type', type: 'Choice', choices: ['New Construction', 'Renovation', 'Other'] },
      { internalName: 'SubmittedBy', displayName: 'Submitted By', type: 'User' },
      { internalName: 'SubmissionDate', displayName: 'Submission Date', type: 'DateTime' },
      { internalName: 'Notes', displayName: 'Notes', type: 'MultiLineText' },
    ],
  },
  {
    title: 'Subcontract Compliance Log',
    description: 'Tracks subcontractor legal and insurance compliance — COIs, bonds, W-9s, and related documentation.',
    template: 100,
    listFamily: 'financial',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Requirement Description', type: 'Text', required: true },
      { internalName: 'SubcontractorName', displayName: 'Subcontractor Name', type: 'Text', required: true },
      { internalName: 'RequirementType', displayName: 'Requirement Type', type: 'Choice', required: true, choices: ['General Liability Insurance', 'Workers Comp Insurance', 'Auto Insurance', 'Professional Liability', 'Umbrella', 'Payment Bond', 'Performance Bond', 'Safety Program', 'OSHA Compliance', 'W-9', 'Other'] },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['Required — Not Received', 'Received', 'Verified', 'Expired', 'Waived'] },
      { internalName: 'DateRequested', displayName: 'Date Requested', type: 'DateTime' },
      { internalName: 'DateReceived', displayName: 'Date Received', type: 'DateTime' },
      { internalName: 'ExpirationDate', displayName: 'Expiration Date', type: 'DateTime' },
      { internalName: 'DocumentLink', displayName: 'Document Link', type: 'URL' },
      { internalName: 'WaiverApproval', displayName: 'Waiver Approval', type: 'Text' },
      { internalName: 'Notes', displayName: 'Notes', type: 'MultiLineText' },
    ],
  },
];
