import type { IListDefinition } from '../services/sharepoint-service.js';

/**
 * W0-G2-T04: Safety-family list definitions for provisioning saga Step 4.
 * Separate module from core HB_INTEL_LIST_DEFINITIONS to preserve G1 regression guard.
 * T07 will combine core + family arrays for provisioning dispatch.
 *
 * JHA is a 3-list parent/child model: JHA Log (parent) → JHA Steps + JHA Attendees (children).
 * Incident Log is flat and complementary to the core Safety Log — no Lookup relationship.
 */
export const SAFETY_LIST_DEFINITIONS: IListDefinition[] = [
  {
    title: 'JHA Log',
    description: 'Job Hazard Analysis parent log tracking JHA documents per work task.',
    template: 100,
    listFamily: 'safety',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Title', type: 'Text', required: true },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['Draft', 'Active', 'Superseded', 'Archived'] },
      { internalName: 'JHADate', displayName: 'JHA Date', type: 'DateTime', required: true },
      { internalName: 'SubcontractorName', displayName: 'Subcontractor Name', type: 'Text' },
      { internalName: 'Supervisor', displayName: 'Supervisor', type: 'User' },
      { internalName: 'CrewSize', displayName: 'Crew Size', type: 'Number' },
      { internalName: 'WorkTask', displayName: 'Work Task', type: 'Text', required: true },
      { internalName: 'Location', displayName: 'Location', type: 'Text' },
      { internalName: 'RequiresConfinedSpacePermit', displayName: 'Requires Confined Space Permit', type: 'Boolean' },
      { internalName: 'ConfinedSpacePermitNumber', displayName: 'Confined Space Permit Number', type: 'Text' },
      { internalName: 'RequiresHotWorkPermit', displayName: 'Requires Hot Work Permit', type: 'Boolean' },
      { internalName: 'HotWorkPermitNumber', displayName: 'Hot Work Permit Number', type: 'Text' },
      { internalName: 'EmergencyContact', displayName: 'Emergency Contact', type: 'Text' },
      { internalName: 'NearestHospital', displayName: 'Nearest Hospital', type: 'Text' },
      { internalName: 'ReviewedBy', displayName: 'Reviewed By', type: 'User' },
      { internalName: 'Notes', displayName: 'Notes', type: 'MultiLineText' },
    ],
  },
  {
    title: 'JHA Steps',
    description: 'Individual job steps linked to a parent JHA Log record with hazards, controls, and PPE.',
    template: 100,
    listFamily: 'safety',
    provisioningOrder: 20,
    parentListTitle: 'JHA Log',
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Title', type: 'Text', required: true },
      { internalName: 'ParentRecord', displayName: 'Parent Record', type: 'Lookup', required: true, lookupListTitle: 'JHA Log', lookupFieldName: 'ID' },
      { internalName: 'StepNumber', displayName: 'Step Number', type: 'Number', required: true },
      { internalName: 'StepDescription', displayName: 'Step Description', type: 'MultiLineText', required: true },
      { internalName: 'Hazards', displayName: 'Hazards', type: 'MultiLineText', required: true },
      { internalName: 'Controls', displayName: 'Controls', type: 'MultiLineText', required: true },
      { internalName: 'PPE_HardHat', displayName: 'PPE Hard Hat', type: 'Boolean' },
      { internalName: 'PPE_SafetyGlasses', displayName: 'PPE Safety Glasses', type: 'Boolean' },
      { internalName: 'PPE_HiVis', displayName: 'PPE Hi-Vis', type: 'Boolean' },
      { internalName: 'PPE_Gloves', displayName: 'PPE Gloves', type: 'Boolean' },
      { internalName: 'PPE_HearingProtection', displayName: 'PPE Hearing Protection', type: 'Boolean' },
      { internalName: 'PPE_Respirator', displayName: 'PPE Respirator', type: 'Boolean' },
      { internalName: 'PPE_Harness', displayName: 'PPE Harness', type: 'Boolean' },
      { internalName: 'PPE_WorkBoots', displayName: 'PPE Work Boots', type: 'Boolean' },
      { internalName: 'PPE_Other', displayName: 'PPE Other', type: 'Text' },
      { internalName: 'RiskLevel', displayName: 'Risk Level', type: 'Choice', choices: ['Low', 'Medium', 'High'] },
    ],
  },
  {
    title: 'JHA Attendees',
    description: 'Crew members who attended and acknowledged a JHA briefing.',
    template: 100,
    listFamily: 'safety',
    provisioningOrder: 20,
    parentListTitle: 'JHA Log',
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Title', type: 'Text', required: true },
      { internalName: 'ParentRecord', displayName: 'Parent Record', type: 'Lookup', required: true, lookupListTitle: 'JHA Log', lookupFieldName: 'ID' },
      { internalName: 'Company', displayName: 'Company', type: 'Text' },
      { internalName: 'AcknowledgedDate', displayName: 'Acknowledged Date', type: 'DateTime' },
      { internalName: 'SignatureMethod', displayName: 'Signature Method', type: 'Choice', choices: ['Physical', 'Digital', 'Verbal Acknowledgment'] },
    ],
  },
  {
    title: 'Incident Log',
    description: 'Safety incident records complementary to the core Safety Log — captures detailed investigation data.',
    template: 100,
    listFamily: 'safety',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Title', type: 'Text', required: true },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['Open', 'Under Investigation', 'Corrective Action', 'Closed'] },
      { internalName: 'IncidentType', displayName: 'Incident Type', type: 'Choice', required: true, choices: ['Near Miss', 'Unsafe Condition', 'Equipment Damage', 'First Aid', 'Medical Treatment', 'Lost Time', 'Fatality', 'Property Damage', 'Other'] },
      { internalName: 'IncidentDate', displayName: 'Incident Date', type: 'DateTime', required: true },
      { internalName: 'ReportedDate', displayName: 'Reported Date', type: 'DateTime' },
      { internalName: 'Location', displayName: 'Location', type: 'Text', required: true },
      { internalName: 'PersonCompleting', displayName: 'Person Completing', type: 'User' },
      { internalName: 'CompanyOfReporter', displayName: 'Company of Reporter', type: 'Text' },
      { internalName: 'EmployeesInvolved', displayName: 'Employees Involved', type: 'MultiLineText' },
      { internalName: 'Description', displayName: 'Description', type: 'MultiLineText', required: true },
      { internalName: 'ImmediateCauses', displayName: 'Immediate Causes', type: 'MultiLineText' },
      { internalName: 'ContributingFactors', displayName: 'Contributing Factors', type: 'MultiLineText' },
      { internalName: 'CorrectiveActions', displayName: 'Corrective Actions', type: 'MultiLineText' },
      { internalName: 'CorrectiveActionsComplete', displayName: 'Corrective Actions Complete', type: 'Boolean' },
      { internalName: 'OSHARecordable', displayName: 'OSHA Recordable', type: 'Boolean' },
      { internalName: 'ReviewedBy', displayName: 'Reviewed By', type: 'User' },
    ],
  },
  {
    title: 'Site Safety Plans',
    description: 'Tracking log for site-specific safety plans, subcontractor SSSPs, and emergency action plans.',
    template: 100,
    listFamily: 'safety',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Title', type: 'Text', required: true },
      { internalName: 'PlanType', displayName: 'Plan Type', type: 'Choice', required: true, choices: ['HBC SSSP', 'Subcontractor SSSP', 'Hurricane Preparedness', 'Emergency Action Plan', 'Other'] },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['Not Submitted', 'Submitted', 'Under Review', 'Approved', 'Expired', 'Superseded'] },
      { internalName: 'SubcontractorName', displayName: 'Subcontractor Name', type: 'Text' },
      { internalName: 'SubmittedDate', displayName: 'Submitted Date', type: 'DateTime' },
      { internalName: 'ApprovedDate', displayName: 'Approved Date', type: 'DateTime' },
      { internalName: 'ExpirationDate', displayName: 'Expiration Date', type: 'DateTime' },
      { internalName: 'DocumentLink', displayName: 'Document Link', type: 'URL' },
      { internalName: 'ReviewedBy', displayName: 'Reviewed By', type: 'User' },
      { internalName: 'Notes', displayName: 'Notes', type: 'MultiLineText' },
    ],
  },
  {
    title: 'Toolbox Talk Log',
    description: 'Daily or weekly toolbox talk records tracking safety briefings and attendance.',
    template: 100,
    listFamily: 'safety',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Title', type: 'Text', required: true },
      { internalName: 'TalkDate', displayName: 'Talk Date', type: 'DateTime', required: true },
      { internalName: 'Facilitator', displayName: 'Facilitator', type: 'User' },
      { internalName: 'AttendeeCount', displayName: 'Attendee Count', type: 'Number' },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['Conducted', 'Missed', 'Rescheduled'] },
      { internalName: 'Notes', displayName: 'Notes', type: 'MultiLineText' },
    ],
  },
  {
    title: 'Safety Walk Log',
    description: 'Safety walk and inspection records tracking findings and resolution status.',
    template: 100,
    listFamily: 'safety',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Title', type: 'Text', required: true },
      { internalName: 'WalkDate', displayName: 'Walk Date', type: 'DateTime', required: true },
      { internalName: 'ConductedBy', displayName: 'Conducted By', type: 'User' },
      { internalName: 'FindingsCount', displayName: 'Findings Count', type: 'Number' },
      { internalName: 'FindingsResolved', displayName: 'Findings Resolved', type: 'Number' },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['Scheduled', 'Conducted', 'Findings Pending', 'Complete'] },
      { internalName: 'Notes', displayName: 'Notes', type: 'MultiLineText' },
    ],
  },
  {
    title: 'Sub Safety Certifications',
    description: 'Subcontractor safety certification and training record tracker.',
    template: 100,
    listFamily: 'safety',
    provisioningOrder: 10,
    fields: [
      { internalName: 'pid', displayName: 'Project ID', type: 'Text', required: true, indexed: true, defaultValue: '{{projectNumber}}' },
      { internalName: 'Title', displayName: 'Title', type: 'Text', required: true },
      { internalName: 'SubcontractorName', displayName: 'Subcontractor Name', type: 'Text', required: true },
      { internalName: 'CertificationType', displayName: 'Certification Type', type: 'Choice', required: true, choices: ['OSHA 10', 'OSHA 30', 'Competent Person', 'Equipment Operator', 'First Aid/CPR', 'Other'] },
      { internalName: 'HolderName', displayName: 'Holder Name', type: 'Text' },
      { internalName: 'IssueDate', displayName: 'Issue Date', type: 'DateTime' },
      { internalName: 'ExpirationDate', displayName: 'Expiration Date', type: 'DateTime' },
      { internalName: 'Status', displayName: 'Status', type: 'Choice', required: true, choices: ['Active', 'Expiring Soon', 'Expired', 'Not Submitted'] },
      { internalName: 'DocumentLink', displayName: 'Document Link', type: 'URL' },
    ],
  },
];
