/**
 * P3-E8-T02 Safety Module record family testing fixtures.
 */

import type {
  ISiteSpecificSafetyPlan,
  ICompletedInspection,
  ISafetyCorrectiveAction,
  IIncidentRecord,
  IJhaRecord,
  ISafetyEvidenceRecord,
} from '../src/safety/records/types.js';

export const createMockSiteSpecificSafetyPlan = (
  overrides: Partial<ISiteSpecificSafetyPlan> = {},
): ISiteSpecificSafetyPlan => ({
  id: 'sssp-001',
  projectId: 'proj-001',
  schemaVersion: 1,
  createdAt: '2026-03-01T00:00:00Z',
  createdBy: 'safety-mgr-001',
  updatedAt: '2026-03-01T00:00:00Z',
  updatedBy: 'safety-mgr-001',
  planVersion: 1,
  status: 'DRAFT',
  approvalDate: null,
  approvedBy: {},
  supersededBy: null,
  effectiveDate: null,
  hazardIdentificationAndControl: {},
  emergencyResponseProcedures: {},
  safetyProgramStandards: {},
  regulatoryAndCodeCitationBlock: {},
  competentPersonRequirements: {},
  subcontractorComplianceStandards: {},
  incidentReportingProtocol: {},
  projectContacts: {},
  subcontractorList: {},
  projectLocation: {},
  emergencyAssemblyAndSiteLayout: {},
  orientationSchedule: {},
  projectSpecificNotes: null,
  renderedDocumentRef: null,
  renderedAt: null,
  ...overrides,
});

export const createMockCompletedInspection = (
  overrides: Partial<ICompletedInspection> = {},
): ICompletedInspection => ({
  id: 'insp-001',
  projectId: 'proj-001',
  schemaVersion: 1,
  createdAt: '2026-03-10T08:00:00Z',
  createdBy: 'safety-mgr-001',
  updatedAt: '2026-03-10T08:00:00Z',
  updatedBy: 'safety-mgr-001',
  templateId: 'tmpl-001',
  templateVersion: 1,
  inspectionDate: '2026-03-10',
  inspectionWeek: '2026-W11',
  inspectorId: 'safety-mgr-001',
  status: 'IN_PROGRESS',
  sectionResponses: [],
  applicableSectionCount: 0,
  rawScore: 0,
  maxPossibleScore: 0,
  normalizedScore: 0,
  correctiveActionIds: [],
  overallNotes: null,
  evidenceRecordIds: [],
  publishedScorecardSnapshot: null,
  ...overrides,
});

export const createMockSafetyCorrectiveAction = (
  overrides: Partial<ISafetyCorrectiveAction> = {},
): ISafetyCorrectiveAction => ({
  id: 'ca-001',
  projectId: 'proj-001',
  schemaVersion: 1,
  createdAt: '2026-03-10T09:00:00Z',
  createdBy: 'safety-mgr-001',
  updatedAt: '2026-03-10T09:00:00Z',
  updatedBy: 'safety-mgr-001',
  sourceType: 'INSPECTION',
  sourceRecordId: 'insp-001',
  sourceDescription: null,
  title: 'Missing guardrail on 3rd floor',
  description: 'Guardrail removed and not replaced after material delivery.',
  severity: 'MAJOR',
  category: 'FALL_PROTECTION',
  assignedToId: 'foreman-001',
  assignedToSubcontractorId: null,
  ownerId: 'safety-mgr-001',
  status: 'OPEN',
  dueDate: '2026-03-12',
  completedDate: null,
  verifiedDate: null,
  verifiedById: null,
  resolutionNotes: null,
  evidenceRecordIds: [],
  isOverdue: false,
  ...overrides,
});

export const createMockIncidentRecord = (
  overrides: Partial<IIncidentRecord> = {},
): IIncidentRecord => ({
  id: 'inc-001',
  projectId: 'proj-001',
  schemaVersion: 1,
  createdAt: '2026-03-15T10:00:00Z',
  createdBy: 'safety-mgr-001',
  updatedAt: '2026-03-15T10:00:00Z',
  updatedBy: 'safety-mgr-001',
  incidentType: 'NEAR_MISS',
  incidentDate: '2026-03-15',
  incidentTime: '09:30',
  location: 'Building A, 2nd Floor',
  privacyTier: 'STANDARD',
  status: 'REPORTED',
  caseNumber: null,
  incidentNarrative: 'Worker observed unsecured load on overhead crane.',
  immediateActions: 'Area cordoned off, crane operation halted.',
  rootCauseAnalysis: null,
  preventiveMeasures: null,
  personsInvolved: [],
  correctiveActionIds: [],
  evidenceRecordIds: [],
  relatedIncidentIds: [],
  ...overrides,
});

export const createMockJhaRecord = (
  overrides: Partial<IJhaRecord> = {},
): IJhaRecord => ({
  id: 'jha-001',
  projectId: 'proj-001',
  schemaVersion: 1,
  createdAt: '2026-03-05T08:00:00Z',
  createdBy: 'safety-mgr-001',
  updatedAt: '2026-03-05T08:00:00Z',
  updatedBy: 'safety-mgr-001',
  activityDescription: 'Steel erection — 3rd floor',
  scopeOfWork: 'Erect structural steel members for 3rd floor framing.',
  location: 'Building A, 3rd Floor',
  applicableSubcontractorIds: ['sub-001'],
  status: 'DRAFT',
  approvedById: null,
  approvedAt: null,
  supersededById: null,
  steps: [
    {
      stepNumber: 1,
      stepDescription: 'Set up perimeter fall protection',
      hazards: [
        {
          hazardDescription: 'Fall from height',
          riskLevel: 'HIGH',
          controlMeasures: ['Install guardrails', 'Require fall harness'],
          residualRiskLevel: 'MEDIUM',
        },
      ],
    },
  ],
  requiredPpe: ['HARD_HAT', 'SAFETY_GLASSES', 'FALL_HARNESS', 'STEEL_TOE_BOOTS'],
  requiresCompetentPerson: true,
  competentPersonDesignationId: null,
  linkedDailyPreTaskIds: [],
  evidenceRecordIds: [],
  ...overrides,
});

export const createMockSafetyEvidenceRecord = (
  overrides: Partial<ISafetyEvidenceRecord> = {},
): ISafetyEvidenceRecord => ({
  id: 'evi-001',
  projectId: 'proj-001',
  schemaVersion: 1,
  createdAt: '2026-03-10T09:15:00Z',
  createdBy: 'safety-mgr-001',
  updatedAt: '2026-03-10T09:15:00Z',
  updatedBy: 'safety-mgr-001',
  sourceRecordType: 'INSPECTION',
  sourceRecordId: 'insp-001',
  fileName: 'guardrail-deficiency.jpg',
  fileSizeBytes: 2048000,
  mimeType: 'image/jpeg',
  storageRef: 'blob://safety/evi-001',
  capturedAt: '2026-03-10T09:10:00Z',
  capturedBy: 'safety-mgr-001',
  description: 'Photo of missing guardrail on 3rd floor east side.',
  sensitivityTier: 'STANDARD',
  retentionCategory: 'STANDARD_PROJECT',
  retentionHoldNote: null,
  reviewStatus: 'PENDING_REVIEW',
  reviewedById: null,
  reviewedAt: null,
  reviewNotes: null,
  ...overrides,
});
