import type { IFieldWorkPackage } from '../src/schedule/types/index.js';

export const createMockFieldWorkPackage = (
  overrides?: Partial<IFieldWorkPackage>,
): IFieldWorkPackage => ({
  workPackageId: 'wp-001',
  projectId: 'proj-001',
  parentExternalActivityKey: 'src-001::A1000',
  workPackageName: 'Framing — Level 3 East, Crew A',
  workPackageScope: 'Structural framing for Level 3 East wing',
  tradeCode: 'CARP',
  crewId: 'crew-A',
  locationId: 'loc-003',
  plannedStartDate: '2026-04-01',
  plannedFinishDate: '2026-04-15',
  committedStartDate: null,
  committedFinishDate: null,
  actualStartDate: null,
  actualFinishDate: null,
  progressBasis: 'DurationPct',
  reportedProgressPct: null,
  verifiedProgressPct: null,
  authoritativeProgressPct: null,
  quantityPlanned: 100,
  quantityInstalled: null,
  quantityVerified: null,
  quantityUnit: 'LF',
  calendarOverrideId: null,
  readinessStatus: null,
  status: 'Planned',
  ppcIncluded: true,
  createdBy: 'user-001',
  createdAt: '2026-03-20T09:00:00Z',
  lastModifiedBy: null,
  lastModifiedAt: null,
  syncStatus: 'Synced',
  ...overrides,
});
