import type { IDelayRecord } from '../src/constraints/delay-ledger/types.js';

export const createMockDelayRecord = (
  overrides?: Partial<IDelayRecord>,
): IDelayRecord => ({
  delayId: 'del-001',
  projectId: 'proj-001',
  delayNumber: 'DEL-001',
  title: 'Structural steel delivery delay',
  eventDescription:
    'Structural steel fabricator notified GC on 2026-01-20 that delivery of Building A steel package will be delayed by approximately 14 calendar days due to raw material shortage at the mill. This impacts the critical path erection sequence for floors 3-5.',
  delayEventType: 'PROCUREMENT',
  responsibleParty: 'THIRD_PARTY',
  dateIdentified: '2026-01-20',
  identifiedBy: 'user-001',
  parentConstraintId: null,
  status: 'Identified',
  statusDate: '2026-01-20',
  delayStartDate: '2026-01-15',
  delayEndDate: null,
  notificationDate: null,
  notificationReference: null,
  scheduleReferenceMode: 'ManualFallback',
  scheduleVersionId: null,
  controlScheduleName: 'BL Rev 2 — 2025-Q4 Update',
  controlScheduleDate: '2025-12-15',
  impactedActivityIds: [],
  impactedActivityFreeText: ['Steel Erection — Building A Floors 3-5', 'Metal Deck — Building A Floors 3-5'],
  impactedPathDescription:
    'Critical path sequence: steel fabrication → delivery → erection floors 3-5 → metal deck → concrete pour. Delay at fabrication stage propagates through entire vertical structural sequence.',
  criticalPathImpact: 'UNKNOWN',
  timeImpact: null,
  commercialImpact: null,
  dispositionOutcome: null,
  dispositionNotes: null,
  dateClosed: null,
  closureReason: null,
  evidenceAttachments: [],
  comments: [],
  linkedChangeEventIds: [],
  createdAt: '2026-01-20T09:00:00Z',
  createdBy: 'user-001',
  lastEditedAt: null,
  lastEditedBy: null,
  ...overrides,
});
