import type { IIssuedPermit } from '../src/permits/records/types.js';

export const createMockIssuedPermit = (
  overrides?: Partial<IIssuedPermit>,
): IIssuedPermit => ({
  issuedPermitId: 'permit-001',
  projectId: 'proj-001',
  applicationId: 'app-001',
  permitNumber: 'BP-2026-001234',
  permitType: 'MASTER_BUILDING',
  threadRootPermitId: null,
  parentPermitId: null,
  threadRelationshipType: 'THREAD_ROOT',
  jurisdictionName: 'City of Austin Development Services',
  jurisdictionContact: { contactName: 'Jane Doe', title: 'Plan Reviewer', phone: '(512) 555-0100', email: 'jdoe@austintexas.gov', address: null, officeHours: 'M-F 8am-5pm', portalUrl: 'https://abc.austintexas.gov' },
  applicationDate: '2026-01-15',
  issuanceDate: '2026-03-01',
  expirationDate: '2027-03-01T23:59:59Z',
  renewalDate: null,
  closedDate: null,
  currentStatus: 'ACTIVE',
  currentStatusSetAt: '2026-03-01T10:00:00Z',
  currentStatusSetByActionId: 'action-001',
  permitFeeAmount: 2500,
  bondAmount: 0,
  description: 'Master building permit for Building A — 5-story office building',
  conditions: ['Erosion control measures must be in place before excavation'],
  tags: ['Building A', 'Phase 1'],
  accountableRole: 'PROJECT_MANAGER',
  currentResponsiblePartyId: 'user-002',
  currentResponsiblePartyType: 'USER',
  nextActionOwnerId: null,
  watcherPartyIds: ['user-003'],
  escalationOwnerId: null,
  blockedByPartyId: null,
  daysToExpiration: 365,
  expirationRiskTier: 'LOW',
  derivedHealthTier: 'NORMAL',
  createdAt: '2026-03-01T10:00:00Z',
  updatedAt: '2026-03-01T10:00:00Z',
  createdByUserId: 'user-001',
  ...overrides,
});
