import type { IImportedActivitySnapshot } from '../src/schedule/types/index.js';

export const createMockImportedActivitySnapshot = (
  overrides?: Partial<IImportedActivitySnapshot>,
): IImportedActivitySnapshot => ({
  snapshotId: 'snap-001',
  versionId: 'ver-001',
  projectId: 'proj-001',
  externalActivityKey: 'src-001::A1000',
  sourceActivityCode: 'A1000',
  activityName: 'Excavation & Grading',
  activityType: 'TT_Task',
  statusCode: 'TK_Active',
  wbsCode: 'WBS-01',
  wbsName: 'Site Work',
  targetDurationHrs: 240,
  remainingDurationHrs: 120,
  actualDurationHrs: 120,
  baselineStartDate: '2026-02-01T00:00:00Z',
  baselineFinishDate: '2026-04-01T00:00:00Z',
  targetStartDate: '2026-02-01T00:00:00Z',
  targetFinishDate: '2026-04-15T00:00:00Z',
  actualStartDate: '2026-02-03T00:00:00Z',
  actualFinishDate: null,
  totalFloatHrs: 80,
  freeFloatHrs: 40,
  percentComplete: 50,
  percentCompleteBasis: 'Duration',
  calendarId: 'cal-001',
  calendarName: 'Standard 5-Day',
  constraintType1: null,
  constraintDate1: null,
  constraintType2: null,
  constraintDate2: null,
  predecessors: [{ activityCode: 'A0900', relationshipType: 'FS', lagHrs: 0 }],
  successors: [{ activityCode: 'A1100', relationshipType: 'FS', lagHrs: 0 }],
  resources: [{ resourceCode: 'R-EXC-01', resourceName: 'Excavation Crew', role: 'Primary' }],
  deleteFlag: false,
  importedAt: '2026-03-15T10:00:00Z',
  activityCodeValues: [{ codeType: 'Phase', codeValue: 'SITEWORK', codeDescription: 'Site Work Phase' }],
  udfValues: [],
  primaryResourceCode: 'R-EXC-01',
  primaryResponsibleUserId: 'user-super-001',
  tradeCode: 'EXC',
  phaseCode: 'SITEWORK',
  areaCode: 'AREA-A',
  contractMilestoneFlag: false,
  ...overrides,
});
