import type { ActionDescriptor, CanonicalPnpActionKey } from './types.js';

const EXTRACTION_ARTIFACTS = [
  'raw.json',
  'normalized.json',
  'summary.md',
  'provision-summary.json',
  'seed-summary.json',
  'artifact-manifest.json',
  'artifact-bundle.zip',
] as const;

const ACTIONS: readonly ActionDescriptor[] = [
  {
    actionKey: 'sharepoint-control:extraction:site-template',
    label: 'Site Starting-Point Template Extraction',
    description: 'Captures reusable site structure and baseline assets for starter-template snapshots.',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export'],
  },
  {
    actionKey: 'sharepoint-control:extraction:list-schema',
    label: 'List Schema Extraction',
    description: 'Extracts full list metadata, fields, views, and content types for selected lists.',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-and-list-filter',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export'],
  },
  {
    actionKey: 'sharepoint-control:extraction:page-layout',
    label: 'Page/Layout Extraction',
    description: 'Exports modern page section/control layout composition for selected pages.',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-and-page-filter',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export'],
  },
  {
    actionKey: 'sharepoint-control:extraction:site-inventory',
    label: 'Site Inventory Export',
    description: 'Builds a high-level inventory of lists, libraries, and pages for the target site.',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export'],
  },
  {
    actionKey: 'sharepoint-control:extraction:library-folder-tree',
    label: 'Library Folder Tree Export',
    description: 'Exports folder/subfolder hierarchy for selected document libraries.',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-and-list-filter',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export'],
  },
  {
    actionKey: 'sharepoint-control:extraction:site-groups-summary',
    label: 'Site Groups / Membership Summary Export',
    description: 'Summarizes owners, members, visitors, and membership rollups for a site.',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export'],
  },
  {
    actionKey: 'sharepoint-control:extraction:page-webpart-inventory',
    label: 'Page Webpart Manifest Inventory',
    description: 'Maps client-side webparts used across selected modern pages.',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-and-page-filter',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export'],
  },
  {
    actionKey: 'sharepoint-control:provisioning:priority-actions-band-lists',
    label: 'Provision Priority Actions Band Lists',
    description: 'Creates or normalizes Priority Actions Band Config and Items lists against the schema contract.',
    riskLevel: 'low-impact',
    executionMode: 'apply',
    supportsPreview: false,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['sharepoint-provision', 'sharepoint-provision-and-seed'],
  },
  {
    actionKey: 'sharepoint-control:extraction:homepage-quick-links',
    label: 'Extract Homepage Quick Links',
    description: 'Extracts and normalizes live homepage Quick Links payload for command-band seeding.',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export', 'sharepoint-seed', 'sharepoint-provision-and-seed'],
  },
  {
    actionKey: 'sharepoint-control:provisioning:priority-actions-band-seed-items',
    label: 'Seed Priority Actions Band Items From Quick Links',
    description: 'Seeds command-band config/items from extracted homepage Quick Links with deterministic defaults.',
    riskLevel: 'low-impact',
    executionMode: 'apply',
    supportsPreview: false,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['sharepoint-seed', 'sharepoint-provision-and-seed'],
  },
  {
    actionKey: 'sharepoint-control:provisioning:priority-actions-band-provision-and-seed',
    label: 'Provision And Seed Priority Actions Band',
    description: 'Runs list provisioning, homepage Quick Links extraction, and idempotent item seeding in one workflow.',
    riskLevel: 'low-impact',
    executionMode: 'apply',
    supportsPreview: false,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['sharepoint-provision-and-seed'],
  },
  {
    actionKey: 'sharepoint-control:provisioning:priority-actions-band-seed-curated',
    label: 'Seed Priority Actions Band Curated Catalog',
    description: 'Seeds command-band config and items from repo-owned curated research payload with managed-key archival.',
    riskLevel: 'low-impact',
    executionMode: 'apply',
    supportsPreview: false,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['sharepoint-seed', 'sharepoint-provision-and-seed'],
  },
  {
    actionKey: 'sharepoint-control:provisioning:priority-actions-band-provision-and-seed-curated',
    label: 'Provision And Seed Priority Actions Band (Curated)',
    description: 'Runs list provisioning, then curated config/item seeding from repo-owned research payload in one workflow.',
    riskLevel: 'low-impact',
    executionMode: 'apply',
    supportsPreview: false,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['sharepoint-provision-and-seed'],
  },
  {
    actionKey: 'sharepoint-control:provisioning:flagship-action-layer-cutover',
    label: 'Flagship Action Layer Cutover (Quick Links → PriorityActionsRail)',
    description:
      'Captures the flagship page Quick Links inventory, removes the OOB Quick Links webpart from the target page, and places the governed PriorityActionsRail client-side webpart in its slot. Idempotent.',
    riskLevel: 'low-impact',
    executionMode: 'apply',
    supportsPreview: false,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['sharepoint-provision-and-seed'],
  },
  {
    actionKey: 'sharepoint-control:proof:homepage-action-layer',
    label: 'Homepage Action-Layer Cutover Proof',
    description:
      'Authoritative read-only proof that inspects the live homepage canvas and verifies hero -> PriorityActionsRail -> hbHomepage order with no OOB Quick Links in the action layer.',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export'],
  },
  {
    actionKey: 'sharepoint-control:provisioning:flagship-homepage-wrapper-cutover',
    label: 'Flagship Homepage Wrapper Cutover (standalone rail + Quick Links → HbHomepage-embedded)',
    description:
      'Phase-07 cutover. Removes any residual OOB Quick Links and standalone PriorityActionsRail webparts from the flagship page, leaving only the HB Signature Hero and HbHomepage (which owns the wrapper-embedded rail). Does not add webparts: hbHomepage must already be authored on the page. Idempotent.',
    riskLevel: 'low-impact',
    executionMode: 'apply',
    supportsPreview: false,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['sharepoint-provision-and-seed'],
  },
  {
    actionKey: 'sharepoint-control:proof:homepage-wrapper-embedded',
    label: 'Homepage Wrapper-Embedded Cutover Proof',
    description:
      'Phase-07 authoritative read-only proof that the flagship homepage canvas matches the wrapper-embedded target: hero -> hbHomepage order, no OOB Quick Links, and no standalone PriorityActionsRail webpart (the rail is composed inside HbHomepage).',
    riskLevel: 'read-only',
    executionMode: 'advisory',
    supportsPreview: true,
    available: true,
    unavailableReason: null,
    requiredInput: 'site-only',
    expectedArtifacts: EXTRACTION_ARTIFACTS,
    allowedExecutionIntents: ['read-only-export'],
  },
] as const;

const ALIASES: Record<string, CanonicalPnpActionKey> = {
  'sharepoint:pnp:site-starting-point-template-export': 'sharepoint-control:extraction:site-template',
  'sharepoint:pnp:list-schema-export': 'sharepoint-control:extraction:list-schema',
  'sharepoint:pnp:page-layout-export': 'sharepoint-control:extraction:page-layout',
  'sharepoint:pnp:library-folder-tree-export': 'sharepoint-control:extraction:library-folder-tree',
  'sharepoint:pnp:site-groups-summary-export': 'sharepoint-control:extraction:site-groups-summary',
  'sharepoint:pnp:page-webpart-inventory-export': 'sharepoint-control:extraction:page-webpart-inventory',
  'sharepoint:pnp:priority-actions-band-provision': 'sharepoint-control:provisioning:priority-actions-band-lists',
  'sharepoint:pnp:homepage-quick-links-extract': 'sharepoint-control:extraction:homepage-quick-links',
  'sharepoint:pnp:priority-actions-band-seed': 'sharepoint-control:provisioning:priority-actions-band-seed-items',
  'sharepoint:pnp:priority-actions-band-provision-and-seed': 'sharepoint-control:provisioning:priority-actions-band-provision-and-seed',
  'sharepoint:pnp:priority-actions-band-seed-curated': 'sharepoint-control:provisioning:priority-actions-band-seed-curated',
  'sharepoint:pnp:priority-actions-band-provision-and-seed-curated': 'sharepoint-control:provisioning:priority-actions-band-provision-and-seed-curated',
  'sharepoint:pnp:flagship-action-layer-cutover': 'sharepoint-control:provisioning:flagship-action-layer-cutover',
  'sharepoint:pnp:homepage-action-layer-proof': 'sharepoint-control:proof:homepage-action-layer',
  'sharepoint:pnp:flagship-homepage-wrapper-cutover':
    'sharepoint-control:provisioning:flagship-homepage-wrapper-cutover',
  'sharepoint:pnp:homepage-wrapper-embedded-proof':
    'sharepoint-control:proof:homepage-wrapper-embedded',
};

export function getActions(): readonly ActionDescriptor[] {
  return ACTIONS;
}

export function resolveActionKey(input: string): CanonicalPnpActionKey | null {
  if (ACTIONS.some((action) => action.actionKey === input)) {
    return input as CanonicalPnpActionKey;
  }
  return ALIASES[input] ?? null;
}

export function getActionDescriptor(actionKey: CanonicalPnpActionKey): ActionDescriptor {
  const descriptor = ACTIONS.find((action) => action.actionKey === actionKey);
  if (!descriptor) {
    throw new Error(`Unknown action key: ${actionKey}`);
  }
  return descriptor;
}
