declare const styles: {
  readonly panel: string;
  readonly readiness: string;
  readonly readinessGood: string;
  readonly readinessWarn: string;
  readonly readinessProblem: string;
  readonly galleryCluster: string;
  readonly galleryHeading: string;
  readonly galleryHeadingRow: string;
  readonly galleryHeadingHint: string;
  readonly grid: string;
  readonly leadGrid: string;
  readonly tile: string;
  readonly tileFeatured: string;
  readonly tileBody: string;
  readonly thumbFrame: string;
  readonly thumb: string;
  readonly thumbBroken: string;
  readonly tileCaption: string;
  readonly tileMetaRow: string;
  readonly tileActions: string;
};
export default styles;
