import type { IMyWorkItem } from '../src/types/index.js';

/** Factory for mock `IMyWorkItem` instances */
export function createMockMyWorkItem(overrides?: Partial<IMyWorkItem>): IMyWorkItem {
  return {
    workItemId: 'work-001',
    canonicalKey: 'bic-next-move::rec-001',
    dedupeKey: 'bic-next-move::rec-001::v1',
    class: 'owned-action',
    priority: 'now',
    state: 'active',
    lane: 'do-now',
    title: 'Review Transfer Request',
    summary: 'Transfer request TR-2026-0042 requires your approval.',
    expectedAction: 'Approve or reject the transfer',
    dueDateIso: null,
    isOverdue: false,
    isUnread: true,
    isBlocked: false,
    blockedReason: null,
    changeSummary: null,
    whyThisMatters: null,
    supersededByWorkItemId: null,
    owner: {
      type: 'user',
      id: 'user-001',
      label: 'Jane Doe',
    },
    previousOwner: null,
    context: {
      moduleKey: 'bic',
      projectId: 'proj-001',
      projectCode: 'ACME',
      projectName: 'ACME Corp',
      recordId: 'rec-001',
      recordType: 'transfer',
      href: '/bic/transfers/rec-001',
    },
    sourceMeta: [
      {
        source: 'bic-next-move',
        sourceEventType: 'transfer.created',
        sourceItemId: 'src-001',
        sourceUpdatedAtIso: '2026-01-15T10:00:00.000Z',
        explanation: 'New transfer request assigned to you.',
      },
    ],
    permissionState: {
      canOpen: true,
      canAct: true,
      canDelegate: true,
      canBulkAct: false,
      cannotActReason: null,
    },
    lifecycle: {
      previousStepLabel: null,
      currentStepLabel: 'Pending Approval',
      nextStepLabel: 'Approved',
      blockedDependencyLabel: null,
      impactedRecordLabel: null,
    },
    rankingReason: {
      primaryReason: 'Assigned to you and requires action',
      contributingReasons: ['High-priority transfer', 'Approaching deadline'],
      score: 0.95,
    },
    attentionPolicy: undefined,
    availableActions: [
      { key: 'approve', label: 'Approve', variant: 'primary' },
      { key: 'reject', label: 'Reject', variant: 'danger', requiresConfirmation: true },
    ],
    offlineCapable: false,
    healthState: undefined,
    delegatedBy: null,
    delegatedTo: null,
    locationLabel: null,
    userNote: null,
    timestamps: {
      createdAtIso: '2026-01-15T10:00:00.000Z',
      updatedAtIso: '2026-01-15T10:00:00.000Z',
      markedReadAtIso: null,
      markedDeferredAtIso: null,
      deferredUntilIso: null,
    },
    dedupe: undefined,
    supersession: undefined,
    ...overrides,
  };
}
