declare const styles: {
  readonly surface: string;
  readonly toolbar: string;
  readonly toolbarGroup: string;
  readonly toolbarBtn: string;
  readonly toolbarBtnActive: string;
  readonly toolbarIcon: string;
  readonly editorContent: string;
  readonly editorContentEmpty: string;
  readonly placeholder: string;
  readonly editorArea: string;
  readonly linkPromptPopover: string;
  readonly linkPromptField: string;
  readonly linkPromptFieldLabel: string;
  readonly linkPromptInput: string;
  readonly linkPromptError: string;
  readonly linkPromptActions: string;
  readonly editorFooter: string;
  readonly editorCounts: string;
  readonly editorSupportHint: string;
  readonly editorShortcuts: string;
  readonly editorShortcutsSummary: string;
  readonly editorShortcutsList: string;
  readonly editorShortcutsTerm: string;
  readonly editorShortcutsKeys: string;
};
export default styles;
