export {
  SESSION_DB_NAME,
  SESSION_DB_VERSION,
  DRAFT_STORE_NAME,
  QUEUE_STORE_NAME,
  DRAFT_DEFAULT_TTL_HOURS,
  QUEUE_DEFAULT_MAX_RETRIES,
  SPFX_SYNC_POLL_INTERVAL_MS,
  SYNC_BACKOFF_BASE_MS,
  SYNC_BACKOFF_MAX_MS,
  CONNECTIVITY_PROBE_TIMEOUT_MS,
  CONNECTIVITY_PROBE_INTERVAL_MS,
  AUTO_SAVE_DEBOUNCE_MS,
} from './sessionStateDefaults.js';
