/**
 * PCC (Project Control Center) — shared foundations.
 *
 * Implementation-neutral TypeScript model contracts shared across PCC
 * surfaces (SPFx, backend, fixtures). Source of truth:
 * `docs/architecture/blueprint/sp-project-control-center/Standard_Project_Site_Template_Contract.md`.
 *
 * Boundary discipline (Wave 1 scope lock):
 *   - pure TypeScript, no runtime side effects;
 *   - no SPFx, PnP, Azure SDK, backend runtime, or Procore SDK imports;
 *   - no tenant URLs, no secrets, no API clients;
 *   - legacy enums in `../project/ProjectEnums.ts` and `../auth/ProjectRoles.ts`
 *     are intentionally not mutated.
 *
 * @module pcc
 */

// Branded identifiers
export type {
  PccProjectId,
  PccProjectNumber,
  PccUserId,
  PccWorkflowItemId,
  PccApprovalCheckpointId,
  PccBusinessAuditEventId,
  PccSiteUrl,
} from './types.js';

// Project lifecycle vocabulary
export {
  PCC_PROJECT_STAGES,
  PCC_PROJECT_STATUSES,
  PCC_PROJECT_TYPES,
  type PccProjectStage,
  type PccProjectStatus,
  type PccProjectType,
} from './PccProjectEnums.js';

// Project profile read model
export type { IProjectProfile } from './IProjectProfile.js';

// Personas / roles
export {
  PCC_PERSONAS,
  PCC_PERSONA_LABELS,
  PCC_PERSONA_TIER,
  PCC_PERSONA_CATEGORY,
  PCC_PERSONA_TO_PROJECT_ROLE,
  mapPccPersonaToProjectRole,
  type PccPersona,
  type PccUserRole,
  type PccPersonaTier,
  type PccPersonaCategory,
} from './PccUserRoles.js';

// Work centers (contract template registry — 21 entries from §8.1)
export {
  PCC_WORK_CENTER_IDS,
  PCC_WORK_CENTERS,
  type PccWorkCenterId,
  type PccWorkCenterMvpTier,
  type IPccWorkCenter,
} from './PccWorkCenters.js';

// MVP surfaces (eight Phase 3 PCC app navigation surfaces)
export {
  PCC_MVP_SURFACE_IDS,
  PCC_MVP_SURFACES,
  type PccMvpSurfaceId,
  type PccMvpSurfaceTier,
  type IPccMvpSurface,
} from './PccMvpSurfaces.js';

// Priority actions
export {
  PRIORITY_ACTION_CATEGORIES,
  PRIORITY_ACTION_CATEGORY_LABELS,
  PRIORITY_ACTION_CATEGORY_META,
  type PriorityActionCategory,
  type IPriorityActionCategoryMeta,
  type IPriorityAction,
} from './PriorityActions.js';

// Workflow modules
export {
  PCC_WORKFLOW_MODULE_IDS,
  PCC_WORKFLOW_MODULES,
  type WorkflowModuleId,
  type WorkflowModuleMvpTier,
  type IWorkflowModule,
} from './WorkflowModules.js';

// Workflow items
export {
  WORKFLOW_ITEM_STATUSES,
  WORKFLOW_STATUS_META,
  type WorkflowItemStatus,
  type IWorkflowItem,
  type IWorkflowItemAssignment,
  type IWorkflowItemAssignmentHistoryEntry,
  type IWorkflowItemTransition,
  type IWorkflowStatusMeta,
} from './WorkflowItems.js';

// Business audit
export {
  BUSINESS_AUDIT_SOURCE_CONTEXT_TYPES,
  type BusinessAuditSourceContextType,
  type BusinessAuditSourceContext,
  type IBusinessAuditEvent,
} from './BusinessAuditEvent.js';

// Approval checkpoints
export {
  APPROVAL_CHECKPOINT_STATES,
  APPROVAL_CHECKPOINT_TYPES,
  APPROVAL_AUTHORITY_TYPES,
  REVIEWER_ACTIONS,
  type ApprovalCheckpointState,
  type ApprovalCheckpointType,
  type ApprovalAuthorityType,
  type ReviewerAction,
  type IReviewerActionRecord,
  type IApprovalCheckpoint,
} from './ApprovalCheckpoint.js';

// Comments
export type { IComment, ICommentHistoryEntry } from './Comments.js';

// Feature flags (read-model metadata only)
export {
  PCC_FEATURE_FLAG_IDS,
  PCC_FEATURE_FLAG_POSTURES,
  PCC_FEATURE_FLAGS,
  type PccFeatureFlagId,
  type PccFeatureFlagPosture,
  type IPccFeatureFlag,
} from './PccFeatureFlags.js';

// Module flags (read-model metadata only)
export {
  PCC_MODULE_FLAG_POSTURES,
  PCC_MODULE_FLAGS,
  type PccModuleFlagPosture,
  type IPccModuleFlag,
} from './PccModuleFlags.js';

// Fixture guards (pure utility)
export {
  PCC_FORBIDDEN_FIXTURE_KEYS,
  PCC_FORBIDDEN_FIXTURE_VALUE_PATTERNS,
  findForbiddenFixtureKeys,
  type PccForbiddenFixtureKey,
} from './PccFixtureGuards.js';

// Fixtures
export * from './fixtures/index.js';

// External systems
export {
  EXTERNAL_SYSTEM_IDS,
  EXTERNAL_SYSTEM_POSTURES,
  EXTERNAL_SYSTEM_CATALOG,
  LAUNCH_LINK_STATES,
  EXTERNAL_SYSTEM_REQUIRED_BEFORE,
  type ExternalSystemId,
  type ExternalSystemPosture,
  type ExternalSystemMappingStatus,
  type IntegrationHealthStatus,
  type IExternalSystemLink,
  type IExternalSystemCatalogEntry,
  type LaunchLinkState,
  type ExternalSystemRequiredBefore,
  type ILaunchLinkProjectContext,
  type IExternalSystemMissingConfig,
  type ILaunchLink,
} from './ExternalSystems.js';

// Document Control sources
export {
  DOCUMENT_CONTROL_SOURCE_IDS,
  DOCUMENT_CONTROL_SOURCES,
  DOCUMENT_CONTROL_LANES,
  DOCUMENT_CONTROL_WAVE7_LANES,
  DOCUMENT_CONTROL_LEGACY_TO_WAVE7_LANE,
  DOCUMENT_CONTROL_WAVE7_TO_LEGACY_LANE,
  DOCUMENT_CONTROL_ACTION_IDS,
  DOCUMENT_CONTROL_ACTIONS,
  DOCUMENT_CONTROL_SOURCE_KIND_IDS,
  DOCUMENT_CONTROL_EXTERNAL_SYSTEM_IDS,
  DOCUMENT_CONTROL_SOURCE_HEALTH_STATES,
  DOCUMENT_CONTROL_ACTION_FAMILIES,
  DOCUMENT_CONTROL_ACTION_CODES,
  DOCUMENT_CONTROL_ROLE_CODES,
  DOCUMENT_CONTROL_ROLE_VOCABULARY,
  DOCUMENT_CONTROL_REVIEW_STATES,
  DOCUMENT_CONTROL_REVIEW_TYPES,
  DOCUMENT_CONTROL_UNIVERSAL_HARD_NO_RULES,
  type DocumentControlSourceId,
  type DocumentControlSource,
  type DocumentControlSourcePosture,
  type DocumentControlLinkBehavior,
  type DocumentControlLane,
  type DocumentControlWave7Lane,
  type DocumentControlActionId,
  type DocumentControlActionExecutionState,
  type DocumentControlCapabilityPosture,
  type DocumentControlSourceKindId,
  type DocumentControlExternalSystemId,
  type DocumentControlSourceHealthState,
  type DocumentControlActionFamily,
  type DocumentControlRoleCode,
  type DocumentControlReviewState,
  type DocumentControlReviewType,
  type IDocumentControlSource,
  type IDocumentControlAction,
  type ISharePointBinding,
  type IMyProjectFilesBindingPolicy,
  type IMyProjectFilesBinding,
  type IExternalSourceBinding,
  type ProjectDocumentSourceBinding,
  type IProjectDocumentSourceRegistryEntry,
  type IProjectDocumentSourceHealth,
  type IDocumentControlActionCode,
  type IDocumentControlRoleVocabularyEntry,
  type IDocumentControlRoleActionAuthority,
  type IDocumentControlUniversalHardNoRule,
} from './DocumentControl.js';

// Site Health
export {
  SITE_HEALTH_SEVERITIES,
  REPAIR_TIERS,
  type SiteHealthSeverity,
  type SiteHealthCheckState,
  type SiteHealthRepairTier,
  type ISiteHealthCheck,
  type IDriftIndicator,
  type ISiteHealthSummary,
} from './SiteHealth.js';

// Repair requests
export {
  REPAIR_REQUEST_STATES,
  REPAIR_REQUEST_OWNER_PERSONAS,
  type RepairRequestState,
  type RepairRequestOwnerPersona,
  type IRepairRequest,
} from './RepairRequests.js';

// Settings scopes
export { PCC_SETTINGS_SCOPES, type PccSettingsScope, type IPccSettingsRef } from './PccSettings.js';

// Role-capability matrix (read-model, not auth runtime)
export {
  TEAM_ACCESS_MANAGER_PERSONAS,
  TEAM_ACCESS_LANES,
  TEAM_ACCESS_AUDIENCE_STATES,
  TEAM_ACCESS_MEMBER_KINDS,
  TEAM_ACCESS_REQUEST_STATUSES,
  TEAM_ACCESS_EXECUTION_STATUSES,
  type TeamAccessManagerPersona,
  type TeamAccessLane,
  type TeamAccessAudienceState,
  type TeamAccessMemberKind,
  type TeamAccessRequestStatus,
  type TeamAccessExecutionStatus,
  type ITeamAccessMemberRecord,
  type ITeamAccessCurrentUserContext,
  type ITeamAccessViewerLaneModel,
  type ITeamAccessRequestPreview,
  type ITeamAccessPermissionRequestLaneModel,
  type ITeamAccessAccessManagerLaneModel,
  type ITeamAccessPreviewModel,
} from './TeamAccess.js';

export {
  PCC_CAPABILITY_IDS,
  PCC_CAPABILITIES,
  PCC_PERSONA_CAPABILITIES,
  personaHasCapability,
  type PccCapabilityId,
  type IPccCapability,
} from './PccCapabilities.js';

// Wave 3 Prompt 03 read-model envelope contracts
export {
  PCC_READ_MODEL_MODES,
  PCC_READ_MODEL_SOURCE_STATUSES,
  type PccReadModelMode,
  type PccReadModelSourceStatus,
  type PccReadModelWarning,
  type PccReadModelEnvelope,
  type PccProjectProfileReadModel,
  type PccWorkCenterRegistryReadModel,
  type PccProjectHomeReadModel,
  type PccPriorityActionsReadModel,
  type PccDocumentControlReadModel,
  type PccDocumentControlRoleActionAvailability,
  type PccDocumentControlReviewQueueItem,
  type PccExternalLinksReadModel,
  type PccSiteHealthReadModel,
  type PccTeamAccessReadModel,
  type PccSettingsReadModel,
  type PccResponsibilityMatrixReadModel,
  type PccReadModelResponseMap,
} from './PccReadModels.js';

// Wave 13 Prompt 13B — HB Central Projects Registry + Procore Mapping contract
export {
  PCC_HBCENTRAL_PROJECTS_REGISTRY_FIELD_INTERNAL_NAMES,
  PCC_PROCORE_PROJECT_MAPPING_ALLOWED_TRANSITIONS,
  PCC_PROCORE_PROJECT_MAPPING_DEFAULT_FRESHNESS_BOUNDS_DAYS,
  PCC_PROCORE_PROJECT_MAPPING_FIELD_MUTABILITY,
  PCC_PROCORE_PROJECT_MAPPING_FIELD_MUTABILITY_CLASSES,
  PCC_PROCORE_PROJECT_MAPPING_FRESHNESS_BANDS,
  PCC_PROCORE_PROJECT_MAPPING_OWNER_ROLES,
  PCC_PROCORE_PROJECT_MAPPING_QUERY_CARDINALITY_HINTS,
  PCC_PROCORE_PROJECT_MAPPING_QUERY_FILTER_SHAPES,
  PCC_PROCORE_PROJECT_MAPPING_REMEDIATION_HINTS,
  PCC_PROCORE_PROJECT_MAPPING_STATES,
  PCC_PROCORE_PROJECT_MAPPING_TERMINAL_STATES,
  assertPccProcoreProjectMappingTransition,
  derivePccProcoreMappingFreshnessBand,
  isPccProcoreProjectMappingTransitionAllowed,
  validatePccProcoreProjectMappingLegacyHintBoundary,
  type PccHbCentralProjectsRegistryContext,
  type PccHbCentralProjectsRegistryFieldInternalName,
  type PccHbCentralProjectsRegistryLogicalFieldName,
  type PccHbCentralProjectsRegistryQueryRecommendation,
  type PccProcoreProjectMapping,
  type PccProcoreProjectMappingArchived,
  type PccProcoreProjectMappingCommonFields,
  type PccProcoreProjectMappingConfirmed,
  type PccProcoreProjectMappingConflict,
  type PccProcoreProjectMappingFieldMutabilityClass,
  type PccProcoreProjectMappingFieldName,
  type PccProcoreProjectMappingFreshnessBand,
  type PccProcoreProjectMappingFreshnessBoundsDays,
  type PccProcoreProjectMappingModuleIdentity,
  type PccProcoreProjectMappingOwnerRole,
  type PccProcoreProjectMappingProposed,
  type PccProcoreProjectMappingQueryCardinalityHint,
  type PccProcoreProjectMappingQueryFilterShape,
  type PccProcoreProjectMappingReadModel,
  type PccProcoreProjectMappingRemediationHint,
  type PccProcoreProjectMappingSourcePosture,
  type PccProcoreProjectMappingStale,
  type PccProcoreProjectMappingState,
  type PccProcoreProjectMappingTerminalState,
  type PccProcoreProjectMappingTransitionGuardOptions,
  type PccProcoreProjectMappingUnmapped,
} from './PccProcoreProjectMapping.js';

// Re-export the buyout-log read-model union member type alias under the
// PccReadModels barrel so consumers can import it alongside other read-model
// envelope types. The concrete contract lives in BuyoutLog.ts.

export {
  type PccUnifiedLifecycleReadModel,
  type PccProjectLifecycleTimelineReadModel,
  type PccProjectMemoryReadModel,
  type PccProjectLensesReadModel,
  type PccProjectTraceabilityReadModel,
  type PccWarrantyTraceReadModel,
  type PccCrossProjectKnowledgeReadModel,
  type PccUnifiedSearchAskHbiReadModel,
} from './UnifiedLifecycleReadModels.js';

// Wave 12 Prompt 02 — Constraints Log shared model contracts
export {
  CONSTRAINTS_LOG_ITEM_TYPES,
  CONSTRAINTS_LOG_SEED_CATEGORY_IDS,
  CONSTRAINTS_LOG_AUDIT_EVENT_TYPES,
  IMPACT_DIMENSION_IDS,
  IMPACT_LABELS,
  LIKELIHOOD_LABELS,
  URGENCY_LABELS,
  SCORE_LEVELS,
  SEVERITY_BAND_KEYS,
  SEVERITY_OVERRIDE_CODES,
  SEVERITY_OVERRIDE_RULES,
  EXPOSURE_BANDS,
  RISK_STATES,
  RISK_ALLOWED_TRANSITIONS,
  CONSTRAINT_STATES,
  CONSTRAINT_ALLOWED_TRANSITIONS,
  computeGoverningImpactScore,
  computeRiskScore,
  computeResidualRiskScore,
  computeConstraintExposureScore,
  mapSeverityBand,
  applySeverityOverride,
  assertResidualReductionAllowed,
  isRiskTransitionAllowed,
  isConstraintTransitionAllowed,
  type ConstraintsLogItemType,
  type ConstraintsLogSeedCategoryId,
  type ConstraintsLogSeedCategory,
  type ConstraintsLogAuditEventType,
  type ConstraintsLogAuditEvent,
  type ImpactDimensionId,
  type ImpactLabel,
  type LikelihoodLabel,
  type UrgencyLabel,
  type ScoreLevel,
  type LikelihoodLevel,
  type ImpactLevel,
  type UrgencyLevel,
  type ImpactScores,
  type SeverityBandKey,
  type SeverityOverrideCode,
  type SeverityOverrideRule,
  type SeverityOverrideOutcome,
  type ExposureBandDefinition,
  type RiskState,
  type ConstraintState,
  type RiskScoreAssessment,
  type ResidualRiskAssessment,
  type ConstraintExposureAssessment,
  type RiskItem,
  type ConstraintItem,
  type ConstraintsLogReferenceSeams,
  type ConstraintsLogExposureSummary,
  type ConstraintsLogSourcePosture,
  type ConstraintsLogSnapshot,
  type ConstraintsLogModuleIdentity,
  type ConstraintsLogRiskMatrixConfig,
  type IConstraintsLogWorkbookSourceRef,
  type PccConstraintsLogReadModel,
} from './ConstraintsLog.js';

// Wave 13 Prompt 02 — Buyout Log shared model contracts
export {
  BUYOUT_PACKAGE_STATES,
  BUYOUT_PACKAGE_TERMINAL_STATES,
  BUYOUT_PACKAGE_REFERENCE_POSTURE_STATES,
  BUYOUT_PACKAGE_ALLOWED_TRANSITIONS,
  BUYOUT_RECONCILIATION_STATES,
  BUYOUT_COMPLETION_GATE_RESULTS,
  BUYOUT_EXCEPTION_REASON_CODES,
  BUYOUT_EXCEPTION_CLASSIFICATIONS,
  BUYOUT_EXCEPTION_CLASSIFICATION_BY_CODE,
  BUYOUT_FIELD_MUTABILITY_CLASSES,
  BUYOUT_FIELD_MUTABILITY,
  BUYOUT_SOURCE_SYSTEMS,
  BUYOUT_RECORD_CREATION_SOURCES,
  BUYOUT_COMPLIANCE_REQUIREMENT_TYPES,
  BUYOUT_COMPLIANCE_REQUIREMENT_STATES,
  BUYOUT_PROCUREMENT_MILESTONE_TYPES,
  BUYOUT_PROCUREMENT_MILESTONE_STATES,
  BUYOUT_PROCUREMENT_RISK_LEVELS,
  BUYOUT_RECONCILIATION_ISSUE_KINDS,
  BUYOUT_AUDIT_EVENT_TYPES,
  BUYOUT_HBI_REFUSAL_REASONS,
  BUYOUT_PROJECT_MEMORY_KINDS,
  BUYOUT_TRACEABILITY_EDGE_KINDS,
  isBuyoutPackageTransitionAllowed,
  assertBuyoutPackageTransition,
  evaluateBuyoutCompletionGate,
  validateBuyoutWaiver,
  reconcileBuyoutAmounts,
  requireBuyoutSourceLineage,
  isBuyoutHbiEligible,
  buyoutPriorityActionDedupeKey,
  type BuyoutPackageState,
  type BuyoutPackageTerminalState,
  type BuyoutPackageReferencePostureState,
  type BuyoutReconciliationState,
  type BuyoutCompletionGateResult,
  type BuyoutExceptionReasonCode,
  type BuyoutExceptionClassification,
  type BuyoutFieldMutabilityClass,
  type BuyoutSourceSystem,
  type BuyoutRecordCreationSource,
  type BuyoutComplianceRequirementType,
  type BuyoutComplianceRequirementState,
  type BuyoutProcurementMilestoneType,
  type BuyoutProcurementMilestoneState,
  type BuyoutProcurementRiskLevel,
  type BuyoutReconciliationIssueKind,
  type BuyoutAuditEventType,
  type BuyoutHbiRefusalReason,
  type BuyoutProjectMemoryKind,
  type BuyoutTraceabilityEdgeKind,
  type BuyoutPackageTransitionGuardOptions,
  type BuyoutCompletionGateChildren,
  type BuyoutCompletionGateOutcome,
  type BuyoutReconciliationOptions,
  type BuyoutReconciliationOutcome,
  type BuyoutHbiEligibilityResult,
  type IBuyoutWorkbookSourceRef,
  type BuyoutSourceLineage,
  type BuyoutReferenceSeams,
  type BuyoutScopeLine,
  type BuyoutBudgetAllocation,
  type BuyoutCommitmentLink,
  type BuyoutComplianceRequirement,
  type BuyoutProcurementMilestone,
  type BuyoutEvidenceLink,
  type BuyoutReconciliationIssue,
  type BuyoutAuditEvent,
  type BuyoutPriorityActionCandidate,
  type BuyoutProjectMemoryContribution,
  type BuyoutTraceabilityEdgeContribution,
  type BuyoutHbiEligibilityMarker,
  type BuyoutPackage,
  type BuyoutLogModuleIdentity,
  type BuyoutSourcePosture,
  type BuyoutSnapshot,
  type PccBuyoutLogReadModel,
} from './BuyoutLog.js';

// Wave 8 Prompt 02 — Project Readiness Module Framework contracts
export {
  PROJECT_READINESS_DOMAINS,
  PROJECT_READINESS_LIFECYCLE_GATES,
  PROJECT_READINESS_SOURCE_MODULES,
  PROJECT_READINESS_STATUSES,
  PROJECT_READINESS_POSTURES,
  PROJECT_READINESS_BLOCKER_STATES,
  PROJECT_READINESS_SEVERITIES,
  PROJECT_READINESS_CONFIDENCE_STATES,
  PROJECT_READINESS_EVIDENCE_STATES,
  type ProjectReadinessDomainId,
  type ProjectReadinessLifecycleGateId,
  type ProjectReadinessSourceModuleId,
  type ProjectReadinessStatus,
  type ProjectReadinessPosture,
  type ProjectReadinessBlockerState,
  type ProjectReadinessSeverity,
  type ProjectReadinessConfidenceState,
  type ProjectReadinessEvidenceState,
  type IProjectReadinessSourceLineage,
  type IProjectReadinessEvidenceRequirement,
  type IProjectReadinessItem,
  type IProjectReadinessDomainSummary,
  type IProjectReadinessGateSummary,
  type IProjectReadinessOwnershipSummary,
  type IProjectReadinessEvidenceSummary,
  type IProjectReadinessBlockerSummary,
  type IProjectReadinessSourceHealthSummary,
  type IProjectReadinessFrameworkSnapshot,
  type PccProjectReadinessFrameworkReadModel,
} from './ProjectReadinessFramework.js';

// Wave 10 Prompt 02 — Permit & Inspection Control Center contracts
export {
  PERMIT_STATUSES,
  INSPECTION_STATUSES,
  INSPECTION_RESULT_STATUSES,
  FEE_STATUSES,
  EVIDENCE_STATUSES,
  JURISDICTION_TYPES,
  SOURCE_CLASSIFICATIONS,
  RELATED_RECORD_TYPES,
  PERMIT_INSPECTION_SOURCE_FAMILIES,
  PERMIT_INSPECTION_CHECKPOINT_KINDS,
  PERMIT_INSPECTION_READINESS_POSTURES,
  type PermitStatus,
  type InspectionStatus,
  type InspectionResultStatus,
  type FeeStatus,
  type EvidenceStatus,
  type JurisdictionType,
  type SourceClassification,
  type RelatedRecordType,
  type PermitInspectionSourceFamily,
  type PermitInspectionCheckpointKind,
  type PermitInspectionReadinessPosture,
  type IPermitInspectionSourceLineage,
  type IPermitInspectionEvidenceLink,
  type IPermitInspectionAuditEvent,
  type IPermitInspectionTransition,
  type IAhjJurisdictionProfile,
  type IPermitRecord,
  type IInspectionRecord,
  type IReinspectionLineage,
  type IFeeExposureRecord,
  type IPermitInspectionPriorityActionSignal,
  type IPermitInspectionReadinessSignal,
  type IPermitInspectionApprovalSignal,
  type IPermitInspectionControlCenterSummary,
  type IPermitInspectionControlCenterReadModel,
  type PccPermitInspectionControlCenterReadModel,
} from './PermitInspectionControlCenter.js';

// Wave 9 Prompt 02 — Project Lifecycle Readiness Center contracts
export {
  LIFECYCLE_READINESS_FAMILIES,
  LIFECYCLE_READINESS_LIBRARY_TOTAL,
  LIFECYCLE_READINESS_LIBRARY_FAMILY_COUNTS,
  LIFECYCLE_READINESS_PHASES,
  LIFECYCLE_READINESS_DOMAINS,
  LIFECYCLE_READINESS_ITEM_TYPES,
  LIFECYCLE_READINESS_CRITICALITY_LEVELS,
  LIFECYCLE_READINESS_STATUSES,
  LIFECYCLE_READINESS_EXCEPTION_CODES,
  LIFECYCLE_READINESS_GATES,
  LIFECYCLE_READINESS_EVIDENCE_POLICIES,
  LIFECYCLE_READINESS_OWNERSHIP_CLASSIFICATIONS,
  LIFECYCLE_READINESS_EXTERNAL_REFERENCE_SYSTEMS,
  LIFECYCLE_READINESS_RECURRENCE_CADENCES,
  type LifecycleReadinessFamily,
  type LifecycleReadinessPhaseId,
  type LifecycleReadinessDomainId,
  type LifecycleReadinessItemTypeId,
  type LifecycleReadinessCriticality,
  type LifecycleReadinessStatus,
  type LifecycleReadinessExceptionCode,
  type LifecycleReadinessGateId,
  type LifecycleReadinessEvidencePolicy,
  type LifecycleReadinessOwnershipClassification,
  type LifecycleReadinessExternalReferenceSystem,
  type LifecycleReadinessRecurrenceCadence,
  type ILifecycleReadinessSourceTrace,
  type ILifecycleReadinessEvidenceLink,
  type ILifecycleReadinessExternalReference,
  type ILifecycleReadinessRecurrence,
  type ILifecycleReadinessTemplateItem,
  type ILifecycleReadinessProjectItem,
  type ILifecycleReadinessGateSummary,
  type ILifecycleReadinessDomainSummary,
  type ILifecycleReadinessPhaseSummary,
  type ILifecycleReadinessSourceLibraryMetadata,
  type ILifecycleReadinessSummary,
  type ILifecycleReadinessReadModel,
  type PccLifecycleReadinessReadModel,
} from './LifecycleReadiness.js';

// Wave 11 Prompt 02 — Responsibility Matrix contracts
export {
  RESPONSIBILITY_RACI_VALUES,
  RESPONSIBILITY_CONTRACT_PARTIES,
  RESPONSIBILITY_SOURCE_MARKS,
  RESPONSIBILITY_WORKBOOK_TYPES,
  RESPONSIBILITY_SOURCE_SHEETS,
  RESPONSIBILITY_TEMPLATE_STATUSES,
  RESPONSIBILITY_ITEM_CLASSIFICATIONS,
  RESPONSIBILITY_CRITICALITIES,
  RESPONSIBILITY_DOMAINS,
  RESPONSIBILITY_ASSIGNMENT_LIFECYCLE_STATES,
  RESPONSIBILITY_WORKFLOW_STEP_TYPES,
  RESPONSIBILITY_WORKFLOW_STEP_STATES,
  RESPONSIBILITY_EXCEPTION_CODES,
  RESPONSIBILITY_HEALTH_BANDS,
  RESPONSIBILITY_AUDIT_EVENT_TYPES,
  RESPONSIBILITY_EVIDENCE_LINK_STATES,
  RESPONSIBILITY_MATRIX_LANES,
  type ResponsibilityRaciValue,
  type ResponsibilityContractParty,
  type ResponsibilitySourceMark,
  type ResponsibilityWorkbookType,
  type ResponsibilitySourceSheet,
  type ResponsibilityTemplateStatus,
  type ResponsibilityItemClassification,
  type ResponsibilityCriticality,
  type ResponsibilityDomain,
  type ResponsibilityAssignmentLifecycleState,
  type ResponsibilityWorkflowStepType,
  type ResponsibilityWorkflowStepState,
  type ResponsibilityExceptionCode,
  type ResponsibilityHealthBand,
  type ResponsibilityAuditEventType,
  type ResponsibilityEvidenceLinkState,
  type ResponsibilityMatrixLane,
  type IResponsibilityRoleRef,
  type IResponsibilityPersonRef,
  type IResponsibilityWorkbookSourceRef,
  type IResponsibilityNormalizedAssignment,
  type IResponsibilityContractPartyMapping,
  type IResponsibilityContractObligationRef,
  type IResponsibilityDecisionRights,
  type IResponsibilitySharedAccountabilityException,
  type IResponsibilityAssignment,
  type IResponsibilityWorkflowStepStatusEntry,
  type IResponsibilityWorkflowStep,
  type IResponsibilityHandoff,
  type IResponsibilityException,
  type IResponsibilityEvidenceLinkRef,
  type IResponsibilityTemplateLibraryRecord,
  type IResponsibilityProjectInstanceRecord,
  type IResponsibilityMatrixHealthScoreInsufficient,
  type IResponsibilityMatrixHealthScoreComputed,
  type ResponsibilityMatrixHealthScore,
  type IResponsibilityWorkbookSourceSummary,
  type IResponsibilityMatrixSourcePosture,
  type IResponsibilityMatrixSnapshot,
  type IResponsibilityAuditEvent,
} from './ResponsibilityMatrix.js';

// Wave 99 Prompt 01 — Unified lifecycle contracts
export {
  PCC_PROJECT_LIFECYCLE_STAGES,
  PCC_LIFECYCLE_STAGE_PROJECT_STAGE_MAP,
  PCC_LIFECYCLE_EVENT_TYPES,
  PCC_LIFECYCLE_EVENT_STATUSES,
  PCC_LIFECYCLE_CHECKPOINT_STATUSES,
  PCC_LIFECYCLE_GATE_SIGNAL_STATUSES,
  PCC_MEMORY_RECORD_TYPES,
  PCC_MEMORY_RECORD_STATUSES,
  PCC_PROJECT_LENS_TYPES,
  PCC_PROJECT_LENS_VISIBILITY_MODES,
  PCC_TRACEABLE_RECORD_TYPES,
  PCC_TRACEABILITY_DIRECTIONS,
  PCC_TRACEABILITY_CONFIDENCE,
  PCC_TRACEABILITY_EDGE_TYPES,
  PCC_WARRANTY_TRACE_STATUSES,
  PCC_PROJECT_KNOWLEDGE_REFERENCE_TYPES,
  PCC_CROSS_PROJECT_REFERENCE_STATUSES,
  PCC_REFERENCE_CLASSIFICATIONS,
  PCC_REDACTION_LEVELS,
  PCC_SECURITY_CLASSIFICATIONS,
  PCC_RECORD_OWNERSHIP_POSTURES,
  PCC_HBI_REFUSAL_REASONS,
  type PccProjectLifecycleStage,
  type PccProjectLifecycleEventType,
  type PccProjectLifecycleEventStatus,
  type PccProjectStageTransitionCheckpointStatus,
  type PccLifecycleGateSignalStatus,
  type PccProjectMemoryRecordType,
  type PccProjectMemoryRecordStatus,
  type PccProjectLensType,
  type PccProjectLensVisibilityMode,
  type PccTraceableRecordType,
  type PccTraceabilityEdgeType,
  type PccTraceabilityDirection,
  type PccTraceabilityConfidence,
  type PccWarrantyTraceStatus,
  type PccProjectKnowledgeReferenceType,
  type PccCrossProjectReferenceStatus,
  type PccRecordOwnershipPosture,
  type ProjectLifecycleEventType,
  type ProjectStageTransitionCheckpointStatus,
  type LifecycleGateSignalStatus,
  type ProjectTraceabilityEdgeType,
  type WarrantyTraceStatus,
  type ProjectReferenceClassification,
  type PccRedactionLevel,
  type PccSecurityClassification,
  type PccSourceLineageRef,
  type PccEvidenceLinkRef,
  type PccSecurityPosture,
  type PccRoleStageLensDefinition,
  type PccLifecycleContextReference,
  type PccLifecycleGateSignal,
  type PccProjectStageTransitionCheckpoint,
  type PccProjectTraceabilityEdge,
  type PccProjectLifecycleEvent,
  type PccProjectMemoryRecord,
  type PccProjectDecisionRecord,
  type PccProjectAssumptionRecord,
  type PccProjectStageLens,
  type PccRelatedRecordCluster,
  type PccObligationTraceRecord,
  type PccVendorProductTraceRecord,
  type PccWarrantyResponsibilityRecommendation,
  type PccWarrantyTraceRecord,
  type PccCrossProjectReference,
  type PccProjectKnowledgeReference,
  type PccLifecycleTimelineReadModel,
  type PccProjectMemorySummaryReadModel,
  type PccProjectLensReadModel,
  type PccTraceabilityGraphReadModel,
  type PccClosedProjectReferenceReadModel,
  type LifecycleContextReference,
  type ProjectStageTransitionCheckpoint,
  type LifecycleGateSignal,
  type ProjectLifecycleEvent,
  type ProjectMemoryRecord,
  type ProjectDecisionRecord,
  type ProjectAssumptionRecord,
  type ProjectStageLens,
  type ProjectTraceabilityEdge,
  type WarrantyTraceRecord,
  type CrossProjectReference,
  type ProjectKnowledgeReference,
  type UnifiedSearchGroundingCitation,
  type UnifiedSearchGroundedAnswer,
  type UnifiedSearchRefusal,
  type UnifiedSearchAskHbiResponse,
  type PccHbiRefusalReason,
} from './UnifiedLifecycle.js';
