declare const styles: {
  readonly shellBase: string;
  readonly topContainer: string;
  readonly ribbon: string;
  readonly ribbonLink: string;
  readonly alertBand: string;
  readonly alertItem: string;
  readonly alertInfo: string;
  readonly alertWarning: string;
  readonly alertCritical: string;
  readonly alertMessage: string;
  readonly alertCta: string;
  readonly alertDismiss: string;
  readonly bottomContainer: string;
  readonly footerNav: string;
  readonly footerLink: string;
  readonly supportBand: string;
  readonly supportItem: string;
  readonly supportDescription: string;
  readonly operationalText: string;
};
export default styles;
