/** Auto-generated type declaration for governance.module.css */
declare const styles: {
  readonly actionButton: string;
  readonly tabButton: string;
  readonly tabButtonActive: string;
  readonly toggleChip: string;
  readonly toggleChipActive: string;
  readonly sectionHeading: string;
  readonly infoRow: string;
  readonly infoRowLabel: string;
  readonly toolbarLabel: string;
  readonly errorAlert: string;
  readonly detailStack: string;
  readonly detailProse: string;
  readonly detailSmallProse: string;
  readonly detailRow: string;
  readonly detailRowLabel: string;
  readonly detailReducedView: string;
  readonly dialogBody: string;
  readonly dialogDescription: string;
  readonly dialogInput: string;
  readonly timelineStatus: string;
  readonly timelineList: string;
  readonly timelineEvent: string;
  readonly timelineEventBody: string;
  readonly timelineEventActor: string;
  readonly timelineEventPublic: string;
  readonly timelineEventInternal: string;
};
export default styles;
