/**
 * Admin Control Plane — Observability Probe Contracts
 *
 * Persistence and API contracts for durable infrastructure probe snapshots.
 * These contracts are used by backend adapters, query APIs, and SPFx hooks.
 *
 * The existing `IProbeSnapshot` and `IInfrastructureProbeResult` in
 * `@hbc/features-admin` remain the client-side execution types. These contracts
 * define the backend-owned persistence shape for durable probe history.
 *
 * @module admin-control-plane
 */

import type {
  ObservabilityProbeKind,
  ObservabilityProbeHealthStatus,
} from './ObservabilityEnums.js';

// ─── Probe Result Record ────────────────────────────────────────────────────────

/**
 * A single probe result within a persisted snapshot.
 *
 * This is the normalized persistence shape for individual probe outcomes.
 */
export interface IObservabilityProbeResultRecord {
  /** Unique probe result identifier (UUID v4) */
  readonly probeId: string;

  /** Probe kind identifier */
  readonly probeKey: ObservabilityProbeKind;

  /** Health status determined by the probe */
  readonly status: ObservabilityProbeHealthStatus;

  /** Human-readable summary of the probe outcome */
  readonly summary: string;

  /** ISO 8601 timestamp when the probe observation was made */
  readonly observedAt: string;

  /** Probe-specific metrics (response time, record counts, etc.) */
  readonly metrics: Readonly<Record<string, number | string | boolean>>;

  /** Anomalies detected during the probe, empty array if none */
  readonly anomalies: readonly string[];
}

// ─── Probe Snapshot Record ──────────────────────────────────────────────────────

/**
 * Durable probe snapshot record persisted by the backend observability store.
 *
 * A snapshot captures all probe results from a single execution cycle.
 * Snapshots are append-only — they are never updated after creation.
 */
export interface IObservabilityProbeSnapshotRecord {
  /** Unique snapshot identifier (UUID v4) */
  readonly snapshotId: string;

  /** ISO 8601 timestamp when the snapshot was captured */
  readonly capturedAt: string;

  /** ISO 8601 timestamp when the snapshot was persisted to durable storage */
  readonly persistedAt: string;

  /** Whether this snapshot was triggered by a scheduled cycle or manual operator request */
  readonly triggerMode: 'scheduled' | 'manual';

  /** All probe results in this snapshot */
  readonly results: readonly IObservabilityProbeResultRecord[];

  /** Overall health status — the worst status among all probe results */
  readonly overallStatus: ObservabilityProbeHealthStatus;
}

// ─── Probe Query ────────────────────────────────────────────────────────────────

/**
 * Query filter for listing probe snapshots from the backend.
 */
export interface IObservabilityProbeSnapshotQuery {
  /** Filter by probe kind, null for all probes */
  readonly probeKey: ObservabilityProbeKind | null;

  /** ISO 8601 start of date range, null for no lower bound */
  readonly from: string | null;

  /** ISO 8601 end of date range, null for no upper bound */
  readonly to: string | null;

  /** Pagination cursor from a previous response, null for first page */
  readonly cursor: string | null;

  /** Maximum number of snapshots to return (default 50, max 200) */
  readonly limit: number;
}

// ─── Probe Submission ───────────────────────────────────────────────────────────

/**
 * Payload submitted to the backend when persisting probe results.
 *
 * The client (probe scheduler) submits probe execution results. The backend
 * persists them as a durable snapshot.
 */
export interface IObservabilityProbeSubmissionPayload {
  /** Unique snapshot identifier generated by the client */
  readonly snapshotId: string;

  /** ISO 8601 timestamp when the probes were executed */
  readonly capturedAt: string;

  /** Whether this was a scheduled or manual execution */
  readonly triggerMode: 'scheduled' | 'manual';

  /** Probe results to persist */
  readonly results: readonly IObservabilityProbeResultRecord[];
}

// ─── Probe Health Summary ───────────────────────────────────────────────────────

/**
 * Aggregated probe health summary for dashboard card rendering.
 */
export interface IObservabilityProbeHealthSummary {
  /** Number of probes in healthy state */
  readonly healthyCount: number;

  /** Number of probes in degraded state */
  readonly degradedCount: number;

  /** Number of probes in error state */
  readonly errorCount: number;

  /** Number of probes in unknown state */
  readonly unknownCount: number;

  /** Overall health status (worst across all probes) */
  readonly overallStatus: ObservabilityProbeHealthStatus;

  /** ISO 8601 timestamp of the latest snapshot, null if no snapshots exist */
  readonly lastSnapshotAt: string | null;

  /** Whether the latest snapshot is stale (older than staleness threshold) */
  readonly isStale: boolean;
}
