/**
 * Admin Control Plane — Observability Alert Contracts
 *
 * Persistence and API contracts for durable admin observability alerts.
 * These contracts are used by backend adapters, query APIs, and SPFx hooks.
 *
 * The existing `IAdminAlert` in `@hbc/features-admin` remains the client-side
 * view type. These contracts define the backend-owned persistence shape and
 * are the source of truth for alert state.
 *
 * @module admin-control-plane
 */

import type { AdminDomain } from './AdminEnums.js';
import type { IAdminActorContext } from './IAdminRun.js';
import type {
  ObservabilityAlertSeverity,
  ObservabilityAlertStatus,
  ObservabilityAlertCategory,
  ObservabilityAffectedEntityType,
} from './ObservabilityEnums.js';

// ─── Alert Record ───────────────────────────────────────────────────────────────

/**
 * Durable alert record persisted by the backend observability store.
 *
 * This is the canonical persistence shape. The backend writes these records
 * on alert ingestion and updates them on operator actions (acknowledge, resolve).
 * SPFx reads them through query APIs.
 */
export interface IObservabilityAlertRecord {
  /** Unique alert identifier (UUID v4) */
  readonly alertId: string;

  /** Alert category — maps to the monitor that produced this alert */
  readonly category: ObservabilityAlertCategory;

  /** Current severity level */
  readonly severity: ObservabilityAlertSeverity;

  /** Previous severity level, null if severity has not changed since creation */
  readonly previousSeverity: ObservabilityAlertSeverity | null;

  /** Current lifecycle status */
  readonly status: ObservabilityAlertStatus;

  /** Human-readable alert title */
  readonly title: string;

  /** Human-readable alert description */
  readonly description: string;

  /** Classification of the affected entity */
  readonly affectedEntityType: ObservabilityAffectedEntityType;

  /** Identifier of the affected entity (e.g., project ID, site URL, run ID) */
  readonly affectedEntityId: string;

  /** Admin domain this alert relates to, null if system-wide */
  readonly domain: AdminDomain | null;

  /** Correlated run ID, null if alert is not tied to a specific run */
  readonly runId: string | null;

  /** ISO 8601 timestamp when the alert condition was first detected */
  readonly occurredAt: string;

  /** ISO 8601 timestamp when the alert was ingested into durable storage */
  readonly ingestedAt: string;

  /** ISO 8601 timestamp when the alert was acknowledged, null if not yet acknowledged */
  readonly acknowledgedAt: string | null;

  /** Actor who acknowledged the alert, null if not yet acknowledged */
  readonly acknowledgedBy: IAdminActorContext | null;

  /** ISO 8601 timestamp when the alert was resolved, null if not yet resolved */
  readonly resolvedAt: string | null;

  /** Actor who resolved the alert, null if not yet resolved */
  readonly resolvedBy: IAdminActorContext | null;

  /** Deduplication key generated by the monitor (category:entityType:entityId) */
  readonly dedupeKey: string;

  /** Number of times this alert has been re-evaluated with the same dedupeKey */
  readonly evaluationCount: number;

  /** ISO 8601 timestamp of the most recent evaluation */
  readonly lastEvaluatedAt: string;

  /** Optional CTA label for operator action */
  readonly ctaLabel: string | null;

  /** Optional CTA navigation href */
  readonly ctaHref: string | null;
}

// ─── Alert Ingestion ────────────────────────────────────────────────────────────

/**
 * Payload submitted to the backend alert ingestion API.
 *
 * The client (alert polling service) submits evaluated alerts. The backend
 * deduplicates, persists, and returns the canonical alert records.
 */
export interface IObservabilityAlertIngestionPayload {
  /** Alerts produced by a single monitor evaluation cycle */
  readonly alerts: readonly IObservabilityAlertIngestionItem[];

  /** ISO 8601 timestamp of the evaluation cycle */
  readonly evaluatedAt: string;
}

/**
 * A single alert item within an ingestion payload.
 *
 * This is the shape produced by monitors before backend persistence enrichment.
 */
export interface IObservabilityAlertIngestionItem {
  /** Alert category */
  readonly category: ObservabilityAlertCategory;

  /** Evaluated severity */
  readonly severity: ObservabilityAlertSeverity;

  /** Human-readable title */
  readonly title: string;

  /** Human-readable description */
  readonly description: string;

  /** Affected entity classification */
  readonly affectedEntityType: ObservabilityAffectedEntityType;

  /** Affected entity identifier */
  readonly affectedEntityId: string;

  /** Admin domain, null if system-wide */
  readonly domain: AdminDomain | null;

  /** Correlated run ID, null if not tied to a run */
  readonly runId: string | null;

  /** ISO 8601 timestamp of the alert condition */
  readonly occurredAt: string;

  /** Deduplication key from the monitor */
  readonly dedupeKey: string;

  /** Optional CTA label */
  readonly ctaLabel: string | null;

  /** Optional CTA href */
  readonly ctaHref: string | null;
}

// ─── Alert Query ────────────────────────────────────────────────────────────────

/**
 * Query filter for listing alerts from the backend.
 */
export interface IObservabilityAlertQuery {
  /** Filter by status, null for all statuses */
  readonly status: ObservabilityAlertStatus | null;

  /** Filter by category, null for all categories */
  readonly category: ObservabilityAlertCategory | null;

  /** Filter by severity, null for all severities */
  readonly severity: ObservabilityAlertSeverity | null;

  /** Filter by domain, null for all domains */
  readonly domain: AdminDomain | null;

  /** ISO 8601 start of date range, null for no lower bound */
  readonly from: string | null;

  /** ISO 8601 end of date range, null for no upper bound */
  readonly to: string | null;

  /** Pagination cursor from a previous response, null for first page */
  readonly cursor: string | null;

  /** Maximum number of records to return (default 50, max 200) */
  readonly limit: number;
}

// ─── Alert Summary ──────────────────────────────────────────────────────────────

/**
 * Aggregated alert summary for dashboard badge and card rendering.
 */
export interface IObservabilityAlertSummary {
  /** Count of alerts at critical severity */
  readonly criticalCount: number;

  /** Count of alerts at high severity */
  readonly highCount: number;

  /** Count of alerts at medium severity */
  readonly mediumCount: number;

  /** Count of alerts at low severity */
  readonly lowCount: number;

  /** Total count of active (unresolved) alerts */
  readonly totalActiveCount: number;

  /** ISO 8601 timestamp of the most recent alert, null if no alerts */
  readonly mostRecentAt: string | null;
}
